export const COLORS = {
    // foregrounds
    FOREGROUND_PRIMARY: '#FF9800',
    FOREGROUND_SECONDARY: '#37352F',
    FOREGROUND_TERTIARY: '#A1A09C',
    FOREGROUND_WHITE: '#FFFFFF',
    // backgrounds
    BACKGROUND_PRIMARY: '#FFFFFF',
    BACKGROUND_SECONDARY: '#F7F6F3',
    BACKGROUND_TERTIARY: '#ded2d2',
    BACKGROUND_HIGHLIGHT: '#DAD9D6',
    BACKGROUND_DANGER: '#DC3545',
    // iconic color
    APP_COLOR: '#0EC120',
    PLUGIN_COLOR: '#1C73F5',
};
