export const COLORS = {
    // foregrounds
    FOREGROUND_PRIMARY: '#FF9800',
    FOREGROUND_SECONDARY: '#000000',
    FOREGROUND_TERTIARY: '#707070',
    // backgrounds
    BACKGROUND_PRIMARY: '#FFFFFF',
    BACKGROUND_SECONDARY: '#F7F6F3',
    BACKGROUND_TERTIARY: '#ded2d2',
};
