name: core-app-staging

on:
    push:
        branches:
            - staging

env:
    DOCKER_REPO_NAME: sellerspot/core-app-staging
    K8S_DEPLOYMENT_NAME: core-app-staging
    K8S_DEPLOYMENT_NAMESPACE: staging

jobs:
    staging:
        name: 'core-app-staging'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Make envfile
              uses: SpicyPizza/create-envfile@v1
              with:
                  envKey_NODE_ENV: ${{ secrets.NODE_ENV_STAGING }}
                  envKey_ENV: ${{ secrets.ENV_STAGING }}
                  envKey_APP_NAME: ${{ secrets.APP_NAME_STAGING }}
                  envKey_APP_VERSION: ${{ secrets.APP_VERSION_STAGING }}
                  envKey_PORT: ${{ secrets.PORT_STAGING }}
                  envKey_ONLINE_SERVER_API_URL: ${{ secrets.ONLINE_SERVER_API_URL_STAGING }}
                  envKey_ONLINE_SERVER_SOCKET_URL: ${{ secrets.ONLINE_SERVER_SOCKET_URL_STAGING }}
                  envKey_BASE_DOMAIN_NAME: ${{ secrets.BASE_DOMAIN_NAME_STAGING }}
                  #   directory: <directory_name> # change later
                  #   file_name: .env # change later

            - name: Build and Push Docker Image
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ env.DOCKER_REPO_NAME }}:latest # hold it as latest tag for now, in future we may need to do semantic versioning on docker images

            - name: Docker Image Digest
              run: echo ${{ steps.docker_build.outputs.digest }}

            - name: k8s Update Deployment
              uses: actions-hub/kubectl@master
              env:
                  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_SECRET }}
              with:
                  args: rollout restart deploy ${{ env.K8S_DEPLOYMENT_NAME }} -n ${{ env.K8S_DEPLOYMENT_NAMESPACE }}
