name: core-app-staging

on:
    push:
        branches:
            - staging

env:
    DOCKER_REPO_NAME: sellerspot/core-app-staging
    K8S_DEPLOYMENT_NAME: core-app-staging
    K8S_DEPLOYMENT_NAMESPACE: staging

jobs:
    staging:
        name: 'core-app-staging'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2

            - name: Make .env file
              run: |
                  tee -a .env <<EOF
                  NODE_ENV=${{ secrets.STAGING_NODE_ENV }}
                  ENV=${{ secrets.STAGING_ENV }}
                  APP_NAME=${{ secrets.STAGING_APP_NAME }}
                  APP_VERSION=${{ secrets.STAGING_APP_VERSION }}
                  PORT=${{ secrets.STAGING_PORT }}
                  ONLINE_SERVER_API_URL=${{ secrets.STAGING_ONLINE_SERVER_API_URL }}
                  ONLINE_SERVER_SOCKET_URL=${{ secrets.STAGING_ONLINE_SERVER_SOCKET_URL }}
                  BASE_DOMAIN_NAME=${{ secrets.STAGING_BASE_DOMAIN_NAME }}
                  EOF

            - name: Login, Build, Push Latest, Push Snapshot to DockerHub
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: ${{ env.DOCKER_REPO_NAME }}
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  snapshot: true

            - name: k8s Update Deployment
              uses: actions-hub/kubectl@master
              env:
                  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_SECRET }}
              with:
                  args: rollout restart deploy ${{ env.K8S_DEPLOYMENT_NAME }} -n ${{ env.K8S_DEPLOYMENT_NAMESPACE }}
