name: Storybook Deploy Chromatic

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js 12
              uses: actions/setup-node@v2
              with:
                  node-version: 12
            - run: npm install

            - name: Running eslint
              run: npm run lint

            - name: Running StyleLint
              run: npx stylelint "**/*.scss"

            - name: Publish to Chromatic
              uses: chromaui/action@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
