name: Storybook Deploy Netlify

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js 12
              uses: actions/setup-node@v2
              with:
                  node-version: 12
            - run: npm install

            - name: 'Build storybook static site'
              run: npm run build-storybook --if-present

            - name: Deploy to netlify
              uses: netlify/actions/cli@master
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_STORYBOOK_SITE_ID }}
              with:
                  args: deploy --dir=storybook-static --prod
                  secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
