name: Storybook Deploy Chromatic

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Read .nvmrc
              run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
              id: nvm

            - name: Use Node.js (.nvmrc)
              uses: actions/setup-node@v1
              with:
                  node-version: '${{ steps.nvm.outputs.NVMRC }}'
                  registry-url: https://registry.npmjs.org/

            - name: Install Dependencies
              run: npm install

            - name: Running eslint
              run: npm run lint

            - name: Running StyleLint
              run: npm run stylelint

            - name: Publish to Chromatic
              uses: chromaui/action@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  autoAcceptChanges: true
